In [19]:
import pandas as pd
import re
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
#from args import *
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option("display.max_rows", None)

In [23]:
def extract_prediction(response):
    try:
        prediction = re.search("\[(.*?)\]", response).group(1).replace('-', " ")
        #print(prediction)
        return prediction
    except:
        # print(response)
        # print("#" * 20)
        pass



def compute_accuracy(prediction_list, gold_list):
    correct = 0
    for prediction, gold in zip(prediction_list, gold_list):
        if prediction == gold:
            correct = correct + 1
    accuracy = correct / len(gold_list)
    return accuracy

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:3: SyntaxWarning: invalid escape sequence '\['
/tmp/ipykernel_1150088/1352262767.py:3: SyntaxWarning: invalid escape sequence '\['
  prediction = re.search("\[(.*?)\]", response).group(1).replace('-', " ")


In [24]:
def Get_Prediction(df, prompt, version, df_classification_report):
    prediction_list = []
    for response in df["agg_response"]:
        #print(response)
        prediction = extract_prediction(response)
        prediction_list.append(prediction)

    df["Prediction"]= prediction_list
    #print(prediction_list)

    gold_list = df["label"].to_list()
    
    acc = compute_accuracy(prediction_list, gold_list)
    print(f"Accuracy: {acc: .3f}")

    target_names = ["TRUE", "HALF TRUE", "FALSE"]
    label_map = {"TRUE": 0, "HALF TRUE": 1, "FALSE": 2}
    labels = [label_map[e] for e in gold_list]
    predictions = [label_map[e] for e in prediction_list]
    print("Classification Report")
    print("=" * 60)
    report= classification_report(labels, predictions,
                                  target_names=target_names, digits=4,output_dict=True)
    #print(report)
    df_report = pd.DataFrame(report).transpose()
    df_report["prompt"]= prompt
    df_report["version"]= version
    df_classification_report= pd.concat([df_classification_report, df_report], axis=0)
    #print(df_classification_report)
    #csv_name= "./Results/evaluate
    #df_classification_report.to_csv(csv_name)
    print(confusion_matrix(labels, predictions))
    return df_classification_report

In [14]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

In [15]:
fewshot= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_fewshot_V1.0.json")
df_classification_report= Get_Prediction(fewshot, "fewshot", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.493
Classification Report
[[10 35  5]
 [ 0 40 10]
 [ 0 26 24]]
               prompt version  precision    recall  f1-score     support
TRUE          fewshot    V1.0   1.000000  0.200000  0.333333   50.000000
HALF TRUE     fewshot    V1.0   0.396040  0.800000  0.529801   50.000000
FALSE         fewshot    V1.0   0.615385  0.480000  0.539326   50.000000
accuracy      fewshot    V1.0   0.493333  0.493333  0.493333    0.493333
macro avg     fewshot    V1.0   0.670475  0.493333  0.467487  150.000000
weighted avg  fewshot    V1.0   0.670475  0.493333  0.467487  150.000000


/tmp/ipykernel_1013383/1300868186.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [19]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

novice= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_novice_questions_V1.0.json")
df_classification_report= Get_Prediction(novice, "novice", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.427
Classification Report
[[ 6 44  0]
 [ 1 46  3]
 [ 0 38 12]]
              prompt version  precision    recall  f1-score     support
TRUE          novice    V1.0   0.857143  0.120000  0.210526   50.000000
HALF TRUE     novice    V1.0   0.359375  0.920000  0.516854   50.000000
FALSE         novice    V1.0   0.800000  0.240000  0.369231   50.000000
accuracy      novice    V1.0   0.426667  0.426667  0.426667    0.426667
macro avg     novice    V1.0   0.672173  0.426667  0.365537  150.000000
weighted avg  novice    V1.0   0.672173  0.426667  0.365537  150.000000


/tmp/ipykernel_1013383/1300868186.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [20]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

jour= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_journalist_questions_V1.0.json")
df_classification_report= Get_Prediction(jour, "journalist", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.473
Classification Report
[[10 38  2]
 [ 1 48  1]
 [ 0 37 13]]
                  prompt version  precision    recall  f1-score     support
TRUE          journalist    V1.0   0.909091  0.200000  0.327869   50.000000
HALF TRUE     journalist    V1.0   0.390244  0.960000  0.554913   50.000000
FALSE         journalist    V1.0   0.812500  0.260000  0.393939   50.000000
accuracy      journalist    V1.0   0.473333  0.473333  0.473333    0.473333
macro avg     journalist    V1.0   0.703945  0.473333  0.425574  150.000000
weighted avg  journalist    V1.0   0.703945  0.473333  0.425574  150.000000


/tmp/ipykernel_1013383/1300868186.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [21]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

noq= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_no_questions_V1.0.json")
df_classification_report= Get_Prediction(noq, "noq", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.520
Classification Report
[[11 39  0]
 [ 0 50  0]
 [ 0 33 17]]
             prompt version  precision  recall  f1-score  support
TRUE            noq    V1.0   1.000000    0.22  0.360656    50.00
HALF TRUE       noq    V1.0   0.409836    1.00  0.581395    50.00
FALSE           noq    V1.0   1.000000    0.34  0.507463    50.00
accuracy        noq    V1.0   0.520000    0.52  0.520000     0.52
macro avg       noq    V1.0   0.803279    0.52  0.483171   150.00
weighted avg    noq    V1.0   0.803279    0.52  0.483171   150.00


/tmp/ipykernel_1013383/1300868186.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [6]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

noq= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_direct_V1.0.json")
df_classification_report= Get_Prediction(noq, "noq", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.436
Classification Report
[[ 9 39  1]
 [ 0 48  2]
 [ 0 42  8]]
             prompt version  precision    recall  f1-score     support
TRUE            noq    V1.0   1.000000  0.183673  0.310345   49.000000
HALF TRUE       noq    V1.0   0.372093  0.960000  0.536313   50.000000
FALSE           noq    V1.0   0.727273  0.160000  0.262295   50.000000
accuracy        noq    V1.0   0.436242  0.436242  0.436242    0.436242
macro avg       noq    V1.0   0.699789  0.434558  0.369651  149.000000
weighted avg    noq    V1.0   0.697774  0.436242  0.370049  149.000000


/tmp/ipykernel_1065088/1300868186.py:26: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [11]:
import math
label_value={'TRUE':0, 'HALF TRUE':1, 'FALSE':2}

prompt_list= ["direct", "fewshot", "novice_questions", "journalist_questions", "no_questions"]
version_list= ['V1.0']

df_RMSE= pd.DataFrame(columns=["prompt","version","RMSE"])
rmse_out=[]
for ver in version_list:
    for prompt in prompt_list:
        file_name= "./PoliResult/out/aggregate/final0_start_150_sample_llama-8b_aggregate_" + prompt + "_" +ver + ".json"
        result= pd.read_json(file_name)
        #print(result.columns)
        prediction_list = []
        for response in result["agg_response"]:
            prediction = extract_prediction(response)
            prediction_list.append(prediction)
        result['prediction']= prediction_list
        
        #print(result)
        loss=0
        for i in range(len(result)):
            label = result.loc[i, 'label']
            prediction= result.loc[i, 'prediction']
            loss= loss + ((label_value[label]- label_value[prediction])**2)
            
        rmse= math.sqrt(loss/len(result))
        rmse_out.append({"prompt": prompt, "version": ver, "RMSE": rmse})

In [14]:
rmse_out

[{'prompt': 'direct', 'version': 'V1.0', 'RMSE': 0.7641286655071019},
 {'prompt': 'fewshot', 'version': 'V1.0', 'RMSE': 0.7788880963698616},
 {'prompt': 'novice_questions', 'version': 'V1.0', 'RMSE': 0.7571877794400365},
 {'prompt': 'journalist_questions',
  'version': 'V1.0',
  'RMSE': 0.752772652709081},
 {'prompt': 'no_questions', 'version': 'V1.0', 'RMSE': 0.6928203230275509}]

In [2]:
import pandas as pd

In [25]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

direct= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_gpt-4o_aggregate_direct_google_search_V1.0.json")
#direct.to_csv("direct_google_gpt.csv")
df_classification_report= Get_Prediction(direct, "direct", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.533
Classification Report
[[17 12 21]
 [ 2 27 21]
 [ 4 10 36]]
              prompt version  precision    recall  f1-score     support
TRUE          direct    V1.0   0.739130  0.340000  0.465753   50.000000
HALF TRUE     direct    V1.0   0.551020  0.540000  0.545455   50.000000
FALSE         direct    V1.0   0.461538  0.720000  0.562500   50.000000
accuracy      direct    V1.0   0.533333  0.533333  0.533333    0.533333
macro avg     direct    V1.0   0.583896  0.533333  0.524569  150.000000
weighted avg  direct    V1.0   0.583896  0.533333  0.524569  150.000000


/tmp/ipykernel_1150088/4081896266.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [27]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

fewshot= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_gpt-4o_aggregate_fewshot_google_search_V1.0.json")
#direct.to_csv("direct_google_gpt.csv")
df_classification_report= Get_Prediction(fewshot, "fewshot", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.560
Classification Report
[[20 16 14]
 [ 6 26 18]
 [ 3  9 38]]
               prompt version  precision  recall  f1-score  support
TRUE          fewshot    V1.0   0.689655    0.40  0.506329    50.00
HALF TRUE     fewshot    V1.0   0.509804    0.52  0.514851    50.00
FALSE         fewshot    V1.0   0.542857    0.76  0.633333    50.00
accuracy      fewshot    V1.0   0.560000    0.56  0.560000     0.56
macro avg     fewshot    V1.0   0.580772    0.56  0.551505   150.00
weighted avg  fewshot    V1.0   0.580772    0.56  0.551505   150.00


/tmp/ipykernel_1150088/4081896266.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [28]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

fewshot= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_gpt-4o_aggregate_novice_questions_google_search_V1.0.json")
#direct.to_csv("direct_google_gpt.csv")
df_classification_report= Get_Prediction(fewshot, "fewshot", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.540
Classification Report
[[21 16 13]
 [ 4 27 19]
 [ 1 16 33]]
               prompt version  precision  recall  f1-score  support
TRUE          fewshot    V1.0   0.807692    0.42  0.552632    50.00
HALF TRUE     fewshot    V1.0   0.457627    0.54  0.495413    50.00
FALSE         fewshot    V1.0   0.507692    0.66  0.573913    50.00
accuracy      fewshot    V1.0   0.540000    0.54  0.540000     0.54
macro avg     fewshot    V1.0   0.591004    0.54  0.540652   150.00
weighted avg  fewshot    V1.0   0.591004    0.54  0.540652   150.00


/tmp/ipykernel_1150088/4081896266.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [29]:
df_classification_report= pd.DataFrame(columns=["prompt","version","precision", "recall" ,"f1-score",  "support" ])

jour= pd.read_json("./PoliResult/out/aggregate/final0_start_150_sample_gpt-4o_aggregate_journalist_questions_google_search_V1.0.json")
#direct.to_csv("direct_google_gpt.csv")
df_classification_report= Get_Prediction(jour, "journalist", "V1.0", df_classification_report)
print(df_classification_report)
df_classification_report.drop(['accuracy', 'macro avg', 'weighted avg'], axis=0, inplace=True)

Accuracy:  0.553
Classification Report
[[18 21 11]
 [ 5 28 17]
 [ 1 12 37]]
                  prompt version  precision    recall  f1-score     support
TRUE          journalist    V1.0   0.750000  0.360000  0.486486   50.000000
HALF TRUE     journalist    V1.0   0.459016  0.560000  0.504505   50.000000
FALSE         journalist    V1.0   0.569231  0.740000  0.643478   50.000000
accuracy      journalist    V1.0   0.553333  0.553333  0.553333    0.553333
macro avg     journalist    V1.0   0.592749  0.553333  0.544823  150.000000
weighted avg  journalist    V1.0   0.592749  0.553333  0.544823  150.000000


/tmp/ipykernel_1150088/4081896266.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_classification_report= pd.concat([df_classification_report, df_report], axis=0)


In [31]:
import math
label_value={'TRUE':0, 'HALF TRUE':1, 'FALSE':2}

prompt_list= ["direct", "fewshot", "novice_questions", "journalist_questions"]
version_list= ['V1.0']

df_RMSE= pd.DataFrame(columns=["prompt","version","RMSE"])
rmse_out=[]
for ver in version_list:
    for prompt in prompt_list:
        file_name= "./PoliResult/out/aggregate/final0_start_150_sample_gpt-4o_aggregate_" + prompt + "_google_search_"+ ver + ".json"
        result= pd.read_json(file_name)
        #print(result.columns)
        prediction_list = []
        for response in result["agg_response"]:
            prediction = extract_prediction(response)
            prediction_list.append(prediction)
        result['prediction']= prediction_list
        
        #print(result)
        loss=0
        for i in range(len(result)):
            label = result.loc[i, 'label']
            prediction= result.loc[i, 'prediction']
            loss= loss + ((label_value[label]- label_value[prediction])**2)
            
        rmse= math.sqrt(loss/len(result))
        rmse_out.append({"prompt": prompt, "version": ver, "RMSE": rmse})

In [35]:
rmse_out

[{'prompt': 'direct', 'version': 'V1.0', 'RMSE': 0.983192080250175},
 {'prompt': 'fewshot', 'version': 'V1.0', 'RMSE': 0.8831760866327847},
 {'prompt': 'novice_questions', 'version': 'V1.0', 'RMSE': 0.8602325267042626},
 {'prompt': 'journalist_questions',
  'version': 'V1.0',
  'RMSE': 0.8286535263104036}]